# Generated by Django 4.1 on 2024-01-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-lastFlagAt']},
        ),
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
