# Generated by Django 4.1 on 2024-01-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_website_options_category_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
    ]
