# Generated by Django 4.1 on 2024-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='baseURL',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='EntryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
