# Generated by Django 5.0.2 on 2024-02-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_websitevisitcount_websiteflagcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='validationWithTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseUrl', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=200)),
                ('init_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('baseUrl', 'prod_name')},
            },
        ),
    ]
