# Generated by Django 5.0.2 on 2024-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_validationwithtime_shown_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='validationForLowStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseUrl', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'unique_together': {('baseUrl', 'prod_name')},
            },
        ),
    ]
