# Generated by Django 5.0.2 on 2024-02-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_validationforlowstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='validationForActivityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseUrl', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('baseUrl', 'prod_name', 'msg')},
            },
        ),
    ]
