# Generated by Django 4.1 on 2024-01-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patternName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseURL', models.CharField(max_length=100)),
                ('webName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Relate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(to='image_feed_analyzer.category')),
                ('website', models.ManyToManyField(to='image_feed_analyzer.website')),
            ],
        ),
    ]
