# Generated by Django 4.1 on 2024-01-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_feed_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='category',
            field=models.ManyToManyField(to='image_feed_analyzer.category'),
        ),
        migrations.DeleteModel(
            name='Relate',
        ),
    ]
