# Generated by Django 4.1 on 2024-01-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_feed_analyzer', '0002_website_category_delete_relate'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='lastFlagAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
