# Generated by Django 4.1 on 2024-01-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_feed_analyzer', '0003_website_lastflagat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
